# Generated by Django 4.1.2 on 2022-10-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('year', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album', to='song.artist', verbose_name='Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('song_number', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='song', to='song.album', verbose_name='Album')),
            ],
            options={
                'unique_together': {('name', 'album')},
            },
        ),
    ]
